### ISSUE TITLE
Nextcloud dashboard?

### ISSUE THREAD

**Issue by samuk** [wechange-eg/cosinnus-cloud#2]
I was wondering if you had considered implementing the Nextcloud dashboard:

https://apps.nextcloud.com/categories/dashboard

It seems like it may have interesting features for my use case, I was wondering if you had decided not to? Or if it's on a to-do list somewhere.

**Comment by saschasommer** [comment]
Hi @samuk,
we are not currently planning to include any extensions or plugins into the wechange-nextcloud, sorry!

**Comment by samuk** [comment]
OK no problem. Thanks for the reply.
